// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: pb/router.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest_Type0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// should not be filled in upstream
	StreamId    string `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	Service     string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	HistorySize uint32 `protobuf:"varint,3,opt,name=historySize,proto3" json:"historySize,omitempty"`
}

func (x *InitRequest_Type0) Reset() {
	*x = InitRequest_Type0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest_Type0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest_Type0) ProtoMessage() {}

func (x *InitRequest_Type0) ProtoReflect() protoreflect.Message {
	mi := &file_pb_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest_Type0.ProtoReflect.Descriptor instead.
func (*InitRequest_Type0) Descriptor() ([]byte, []int) {
	return file_pb_router_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest_Type0) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *InitRequest_Type0) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *InitRequest_Type0) GetHistorySize() uint32 {
	if x != nil {
		return x.HistorySize
	}
	return 0
}

// This same id should be sent with all messages for the registered stream
type InitResponse_Type0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId string `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
}

func (x *InitResponse_Type0) Reset() {
	*x = InitResponse_Type0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse_Type0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse_Type0) ProtoMessage() {}

func (x *InitResponse_Type0) ProtoReflect() protoreflect.Message {
	mi := &file_pb_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse_Type0.ProtoReflect.Descriptor instead.
func (*InitResponse_Type0) Descriptor() ([]byte, []int) {
	return file_pb_router_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse_Type0) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type AnalyzerRequest_Type0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamId  string   `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	MessageId string   `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Logs      []string `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *AnalyzerRequest_Type0) Reset() {
	*x = AnalyzerRequest_Type0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzerRequest_Type0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerRequest_Type0) ProtoMessage() {}

func (x *AnalyzerRequest_Type0) ProtoReflect() protoreflect.Message {
	mi := &file_pb_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerRequest_Type0.ProtoReflect.Descriptor instead.
func (*AnalyzerRequest_Type0) Descriptor() ([]byte, []int) {
	return file_pb_router_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzerRequest_Type0) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AnalyzerRequest_Type0) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AnalyzerRequest_Type0) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AnalyzerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Committed bool `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
}

func (x *AnalyzerResponse) Reset() {
	*x = AnalyzerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_router_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerResponse) ProtoMessage() {}

func (x *AnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_router_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerResponse.ProtoReflect.Descriptor instead.
func (*AnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_pb_router_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzerResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

var File_pb_router_proto protoreflect.FileDescriptor

var file_pb_router_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6b, 0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x30,
	0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x54,
	0x79, 0x70, 0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x22, 0x65, 0x0a, 0x15, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x30, 0x0a, 0x10, 0x41, 0x6e, 0x61, 0x6c, 0x79,
	0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x32, 0x84, 0x01, 0x0a, 0x06, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x54, 0x79, 0x70,
	0x65, 0x30, 0x12, 0x12, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x1a, 0x13, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x12,
	0x16, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x30, 0x1a, 0x11, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_router_proto_rawDescOnce sync.Once
	file_pb_router_proto_rawDescData = file_pb_router_proto_rawDesc
)

func file_pb_router_proto_rawDescGZIP() []byte {
	file_pb_router_proto_rawDescOnce.Do(func() {
		file_pb_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_router_proto_rawDescData)
	})
	return file_pb_router_proto_rawDescData
}

var file_pb_router_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_router_proto_goTypes = []interface{}{
	(*InitRequest_Type0)(nil),     // 0: InitRequest_Type0
	(*InitResponse_Type0)(nil),    // 1: InitResponse_Type0
	(*AnalyzerRequest_Type0)(nil), // 2: AnalyzerRequest_Type0
	(*AnalyzerResponse)(nil),      // 3: AnalyzerResponse
}
var file_pb_router_proto_depIdxs = []int32{
	0, // 0: Router.init_Type0:input_type -> InitRequest_Type0
	2, // 1: Router.routeLog_Type0:input_type -> AnalyzerRequest_Type0
	1, // 2: Router.init_Type0:output_type -> InitResponse_Type0
	3, // 3: Router.routeLog_Type0:output_type -> AnalyzerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_router_proto_init() }
func file_pb_router_proto_init() {
	if File_pb_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest_Type0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse_Type0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzerRequest_Type0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_router_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_router_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_router_proto_goTypes,
		DependencyIndexes: file_pb_router_proto_depIdxs,
		MessageInfos:      file_pb_router_proto_msgTypes,
	}.Build()
	File_pb_router_proto = out.File
	file_pb_router_proto_rawDesc = nil
	file_pb_router_proto_goTypes = nil
	file_pb_router_proto_depIdxs = nil
}
